# Generated by Django 4.2 on 2023-05-31 11:15

from django.db import migrations, models

import api.helpers.upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_publicservervpn_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateservervpn',
            name='config',
            field=models.FileField(db_column='Config', null=True, upload_to=api.helpers.upload_helpers.upload_ovpn),
        ),
    ]
