# Generated by Django 4.2 on 2023-05-31 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_privateservervpn_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mgmtwhitelistedip',
            name='ip',
            field=models.GenericIPAddressField(db_column='IP', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='mgmtwhitelistedip',
            name='name',
            field=models.CharField(db_column='Name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privateserver',
            name='city',
            field=models.CharField(db_column='City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='privateserver',
            name='country',
            field=models.CharField(db_column='Country', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='privateserver',
            name='ip',
            field=models.GenericIPAddressField(db_column='IP', null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='privateserver',
            name='provider',
            field=models.ForeignKey(db_column='ProviderId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.provider'),
        ),
        migrations.AlterField(
            model_name='privateservervm',
            name='name',
            field=models.CharField(db_column='Name', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(db_column='Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicserver',
            name='city',
            field=models.CharField(db_column='City', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicserver',
            name='country',
            field=models.CharField(db_column='Country', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicserver',
            name='password',
            field=models.CharField(db_column='Password', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='publicserver',
            name='provider',
            field=models.ForeignKey(db_column='ProviderId', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.provider'),
        ),
    ]
