# Generated by Django 4.2 on 2023-06-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_mgmtwhitelistedip_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateservervm',
            name='vm_template',
            field=models.CharField(db_column='VmTemplate', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='privateservervm',
            name='vm_disk',
            field=models.IntegerField(db_column='VmDisk', null=True),
        ),
    ]
