# Generated by Django 4.2 on 2023-06-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_privateserver_is_hardened_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateservervm',
            name='vm_cores',
            field=models.IntegerField(db_column='VmCores', null=True),
        ),
        migrations.AlterField(
            model_name='privateservervm',
            name='vm_memory',
            field=models.IntegerField(db_column='VmMemory', null=True),
        ),
    ]
