# Generated by Django 4.2 on 2023-06-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_privateservervm_vm_cores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateservervpn',
            name='private_subnet',
            field=models.CharField(db_column='PrivateSubnet', max_length=50, null=True),
        ),
    ]
