# Generated by Django 4.2 on 2023-06-05 02:03

from django.db import migrations, models

import api.helpers.upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_privateservervpn_private_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateservervpn',
            name='config',
            field=models.FileField(db_column='Config', max_length=200, null=True, upload_to=api.helpers.upload_helpers.upload_ovpn),
        ),
    ]
