# Generated by Django 4.2 on 2023-06-05 02:04

from django.db import migrations, models

import api.helpers.upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_privateservervpn_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicservervpn',
            name='config',
            field=models.FileField(db_column='Config', max_length=200, null=True, upload_to=api.helpers.upload_helpers.upload_ovpn),
        ),
    ]
