# Generated by Django 4.2 on 2023-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_publicservervpn_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateservervpn',
            name='private_subnet_mask',
            field=models.IntegerField(db_column='PrivateSubnetMask', null=True),
        ),
        migrations.AddField(
            model_name='proxmoxsubnet',
            name='proxmox_mask',
            field=models.IntegerField(db_column='ProxmoxMask', null=True),
        ),
        migrations.AddField(
            model_name='publicservervpn',
            name='private_subnet_mask',
            field=models.IntegerField(db_column='PrivateSubnetMask', null=True),
        ),
    ]
