# Generated by Django 4.2 on 2023-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_privateservervpn_private_subnet_mask_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='openvpn_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='sessions_limit',
            field=models.PositiveIntegerField(default='2'),
        ),
    ]
