# Generated by Django 4.2 on 2023-06-11 02:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import api.helpers.upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_appuser_openvpn_sessions_appuser_sessions_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='sessions_limit',
            new_name='openvpn_sessions_limit',
        ),
        migrations.AddField(
            model_name='appuser',
            name='wireguard_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='wireguard_sessions_limit',
            field=models.PositiveIntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='publicservervpn',
            name='config',
            field=models.FileField(db_column='Config', null=True, upload_to=api.helpers.upload_helpers.upload_ovpn),
        ),
        migrations.CreateModel(
            name='PublicServerVpnWireguardClient',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.FileField(db_column='Config', null=True, upload_to=api.helpers.upload_helpers.upload_wireguard)),
                ('client', models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('public_server_vpn', models.ForeignKey(db_column='PublicServerVpnId', on_delete=django.db.models.deletion.CASCADE, to='api.publicservervpn')),
            ],
            options={
                'db_table': 'PublicServerVpnWireguardClients',
            },
        ),
        migrations.CreateModel(
            name='PrivateServerVpnWireguardClients',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config', models.FileField(db_column='Config', null=True, upload_to=api.helpers.upload_helpers.upload_wireguard)),
                ('client', models.ForeignKey(db_column='Client', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('private_server_vpn', models.ForeignKey(db_column='PrivateServerVpnId', on_delete=django.db.models.deletion.CASCADE, to='api.privateservervpn')),
            ],
            options={
                'db_table': 'PrivateServerVpnWireguardClients',
            },
        ),
        migrations.AddField(
            model_name='privateservervpn',
            name='wireguard_clients',
            field=models.ManyToManyField(through='api.PrivateServerVpnWireguardClients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicservervpn',
            name='wireguard_clients',
            field=models.ManyToManyField(through='api.PublicServerVpnWireguardClient', to=settings.AUTH_USER_MODEL),
        ),
    ]
