# Generated by Django 4.2 on 2023-06-21 22:33

from django.db import migrations, models

import api.helpers.upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_privateservervpnwireguardclients_privateservervpnwireguardclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateservervpnwireguardclient',
            name='qr_file',
            field=models.FileField(db_column='QrFile', null=True, upload_to=api.helpers.upload_helpers.upload_wireguard),
        ),
        migrations.AddField(
            model_name='publicservervpnwireguardclient',
            name='qr_file',
            field=models.FileField(db_column='QrFile', null=True, upload_to=api.helpers.upload_helpers.upload_wireguard),
        ),
    ]
