# Generated by Django 4.2 on 2023-07-02 16:46

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_privateservervpnwireguardclient_qr_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicServerOpenvpnSession',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Datetime', default=datetime.datetime(2023, 7, 2, 19, 46, 22, 792618), editable=False)),
                ('server', models.ForeignKey(db_column='ServerId', on_delete=django.db.models.deletion.CASCADE, to='api.publicserver')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PublicServerOpenvpnSessions',
            },
        ),
        migrations.CreateModel(
            name='PrivateServerOpenvpnSession',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Datetime', default=datetime.datetime(2023, 7, 2, 19, 46, 22, 776989), editable=False)),
                ('server', models.ForeignKey(db_column='ServerId', on_delete=django.db.models.deletion.CASCADE, to='api.privateserver')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PrivateServerOpenvpnSessions',
            },
        ),
    ]
