# Generated by Django 4.2 on 2023-07-11 02:49

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_publicserveropenvpnsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateServerVmOpenvpnSession',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Datetime', default=datetime.datetime.now, editable=False)),
                ('server_vm', models.ForeignKey(db_column='ServerVMId', on_delete=django.db.models.deletion.CASCADE, to='api.privateservervm')),
                ('user', models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PrivateServerVMOpenvpnSessions',
            },
        ),
        migrations.AlterField(
            model_name='publicserveropenvpnsession',
            name='date',
            field=models.DateTimeField(db_column='Datetime', default=datetime.datetime.now, editable=False),
        ),
        migrations.DeleteModel(
            name='PrivateServerOpenvpnSession',
        ),
    ]
