# Generated by Django 4.2 on 2023-07-11 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_privateservervmopenvpnsession_and_more'),
    ]

    operations = [
    ]
