# Generated by Django 4.2 on 2023-07-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_publicserveropenvpnsession_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_suspended',
            field=models.BooleanField(db_column='isSuspended', default=False),
        ),
    ]
