# Generated by Django 4.2 on 2023-07-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_appuser_is_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateservervm',
            name='is_enabled',
            field=models.BooleanField(db_column='isEnabled', default=True),
        ),
    ]
