# Generated by Django 4.2 on 2023-08-26 16:55

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_privateservervm_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxmoxIP',
            fields=[
                ('id', models.UUIDField(db_column='Id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(db_column='IP', null=True, protocol='IPv4')),
                ('gateway', models.CharField(db_column='Gateway', max_length=50, null=True)),
                ('is_disabled', models.BooleanField(db_column='IsDisabled', default=False)),
                ('is_reserved', models.BooleanField(db_column='IsReserved', default=False)),
                ('mask', models.IntegerField(db_column='ProxmoxMask', null=True)),
                ('private_server', models.ForeignKey(db_column='PrivateServerId', on_delete=django.db.models.deletion.CASCADE, to='api.privateserver')),
            ],
            options={
                'db_table': 'ProxmoxIPs',
            },
        ),
        migrations.DeleteModel(
            name='ProxmoxSubnet',
        ),
        migrations.AddField(
            model_name='privateservervm',
            name='proxmox_ip',
            field=models.ForeignKey(db_column='ProxmoxIP', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.proxmoxip'),
        ),
    ]
