# Generated by Django 4.2.4 on 2023-09-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_proxmoxip_delete_proxmoxsubnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateservervpn',
            name='config',
            field=models.TextField(db_column='Config', null=True),
        ),
        migrations.AlterField(
            model_name='privateservervpnwireguardclient',
            name='config',
            field=models.TextField(db_column='Config', null=True),
        ),
        migrations.AlterField(
            model_name='privateservervpnwireguardclient',
            name='qr_file',
            field=models.TextField(db_column='QrFile', null=True),
        ),
        migrations.AlterField(
            model_name='publicservervpn',
            name='config',
            field=models.TextField(db_column='Config', null=True),
        ),
        migrations.AlterField(
            model_name='publicservervpnwireguardclient',
            name='config',
            field=models.TextField(db_column='Config', null=True),
        ),
        migrations.AlterField(
            model_name='publicservervpnwireguardclient',
            name='qr_file',
            field=models.TextField(db_column='QrFile', null=True),
        ),
    ]
