# Generated by Django 4.2.4 on 2023-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_privateservervpn_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateserver',
            name='password',
            field=models.CharField(db_column='Password', max_length=1024),
        ),
        migrations.AlterField(
            model_name='privateservervm',
            name='password',
            field=models.CharField(db_column='Password', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='publicserver',
            name='password',
            field=models.CharField(db_column='Password', max_length=1024, null=True),
        ),
    ]
