---
- name: Include vars for OpenVPN installation
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
    - "../vars/empty.yml"

- name: Set facts
  import_tasks: set_facts.yml

- name: Uninstall OpenVPN
  import_tasks: uninstall.yml
  when: openvpn_uninstall

- name: Install OpenVPN
  import_tasks: install.yml
  tags:
    - install

- name: Copy or Generate server keys
  import_tasks: server_keys.yml

# ignoreerrors is required for CentOS/RHEL 6
# http://serverfault.com/questions/477718/sysctl-p-etc-sysctl-conf-returns-error
- name: Enable ipv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    ignoreerrors: true
  failed_when: false
  when: not ci_build

- name: Enable ipv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    ignoreerrors: true
  when: openvpn_server_ipv6_network is defined and not ci_build

- name: Detect firewall type
  import_tasks: firewall.yml
  when:
    - not ci_build
    - manage_firewall_rules
  tags: firewall

- name: Configure SELinux
  import_tasks: selinux.yml
  when: ansible_selinux.status == "enabled"

- name: Compare existing certs against 'clients' variable
  import_tasks: cert_sync_detection.yml
  when: openvpn_sync_certs
  tags:
    - sync_certs

- name: Clients block
  block:
    - name: Generate client keys
      import_tasks: client_keys.yml
      when: tls_auth_required

    - name: Define some variables
      set_fact:
        ca_cert: "{{ ca_cert.content }}"
        tls_auth: '{{ tls_auth.content | default("") }}'

    - name: Generate client config
      #no_log: "{{ openvpn_client_config_no_log }}"
      template:
        src: client.ovpn.j2
        dest: "{{ openvpn_ovpn_dir }}/{{ uuid }}.{{ domain }}-{{ openvpn_proto }}.ovpn"
        owner: root
        group: root
        mode: 0400
      loop: "{{ clients }}"
      loop_control:
        index_var: client_id

    - name: Fetch client config
      fetch:
        src: "{{ openvpn_ovpn_dir }}/{{ uuid }}.{{ domain }}-{{ openvpn_proto }}.ovpn"
        dest: "{{ playbook_dir }}/clients/{{ ansible_host }}/{{ uuid }}.{{ domain }}-{{ openvpn_proto }}.ovpn"
        flat: true
      when: openvpn_fetch_client_configs
      # with_items: "{{ clients }}"

  when: clients is defined

- name: Generate revocation list and clean up
  import_tasks: revocation.yml
  when: >-
    (openvpn_revoke_these_certs is defined)
    or
    (openvpn_sync_certs and cert_sync_certs_to_revoke.stdout_lines | length > 0)

- name: Configure OpenVPN server
  import_tasks: config.yml
